### ISSUE TITLE
Bot is spamming true everywhere

### ISSUE THREAD

**Issue by douglascdev** [DarkVypr/VyprBotV2#1]
![image](https://github.com/DarkVypr/VyprBotV2/assets/38195951/a32ac88f-6749-4a00-9935-fa6ae7b324c2)

**Comment by brendeni1** [comment]
Thanks for bringing this to my attention! It looks like this is fixed for now, had some rouge line of code that still kinda doesn't make sense... If anything like this happens again, be sure to let me know in the same way as earlier!
